apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabniki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uporabniki
  template:
    metadata:
      labels:
        app: uporabniki
    spec:
      containers:
        - image: rso2223s01/uporabniki:latest
          name: uporabniki
          env:
            - name: KUMULUZEE_OPENAPIMP_UI_SPECIFICATIONSERVER
              value: http://rso-dostavi.ga
            - name: KUMULUZEE_OPENAPIMP_SERVERS
              value: http://rso-dostavi.ga/users
            - name: KUMULUZEE_SERVER_CONTEXTPATH
              value: /users
            - name: KUMULUZEE_HEALTH_CHECKS_HTTPHEALTHCHECK0_CONNECTIONURL
              value: http://localhost:8080/users/v1/users
            - name: KUMULUZEE_HEALTH_CHECKS_HTTPHEALTHCHECK1_CONNECTIONURL
              value: http://localhost:8080/users/openapi
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul:8500
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://peanut.db.elephantsql.com:5432/rozavelh
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: rozavelh
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-uporabniki-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /users/health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /users/health/ready
                port: server
              initialDelaySeconds: 20
              periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: uporabniki
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: uporabniki
