kumuluzee:
  name: uporabniki-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://localhost:5432/uporabniki
      username: dbuser
      password: postgres
      pool:
        max-size: 2
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-spec
    scan:
      packages: si.fri.rso.skupina1.uporabniki.api.v1
    servers: http://localhost:8080
    ui:
      mapping: /openapi
      server-auto-config:
        enabled: false
        original-uri-check: false
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UsersDS
      http-health-check:
        - connection-url: http://localhost:8080/v1/users
          type: readyness
        - connection-url: http://localhost:8080/openapi
          type: readyness
  dev:
    scan-libraries:
      - uporabniki-services
      - uporabniki-models
      - uporabniki-lib
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="cdd0bbff-8f86-4910-ad4d-4ee50f6029b5-ls.logit.io"
                                  port="13921" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="all" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
rest-properties:
  maintenance-mode: false
  broken: false
  fault: false
