name: build with Maven and package as Docker image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Rename artifact
        run: cp api/target/uporabniki-api-*.jar uporabniki-api-{{github.ref}}.jar
      - name: Create Release
        uses: ncipollo/release-action@v1.11.0
        with:
          artifactErrorsFailBuild: true
          artifacts: 'uporabniki-api-{{github.ref}}.jar'
          body: Automated Release by GitHub Action CI.
          generateReleaseNotes: true
