name: Build with Maven and package as Docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Rename artifact
        run: cp api/target/uporabniki-api-*.jar uporabniki-api-${{github.ref_name}}.jar
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: uporabniki-api
          path: 'uporabniki-api-*.jar'
      - name: Create Release
        if: ${{ startsWith( github.ref_name, 'v') }}
        uses: ncipollo/release-action@v1.11.0
        with:
          artifactErrorsFailBuild: true
          artifacts: 'uporabniki-api-*.jar'
          body: Automated Release by GitHub Action CI.
          generateReleaseNotes: true
  image:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: uporabniki-api
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
